Metrics/LineLength:
  Max: 80

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/EmptyMethod:
  Enabled: false

Style/SymbolProc:
  Enabled: false
